export const tasks: Task[] = [
  {
    id: 1,
    name: 'Model Awnser',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Alias minima voluptatibus quia! Ullam architecto adipisci quidem impedit, fugit libero omnis voluptate necessitatibus ratione tempora vero placeat id, quaerat iusto consequuntur?',
    status: 'backlog',
    comments: 3,
    createdAt: '08/12/2023',
  },
  {
    id: 2,
    name: 'Another Model',
    description: 'Outra descrição interessante...',
    status: 'inProgress',
    comments: 5,
    createdAt: '09/12/2023',
  },
  {
    id: 3,
    name: 'Third Model',
    description: 'Mais uma descrição cativante...',
    status: 'done',
    comments: 8,
    createdAt: '10/12/2023',
  },
  {
    id: 4,
    name: 'Fourth Model',
    description: 'Descrição do quarto modelo...',
    status: 'toDo',
    comments: 2,
    createdAt: '11/12/2023',
  },
  {
    id: 5,
    name: 'Fifth Model',
    description: 'Descrição do quinto modelo...',
    status: 'toDo',
    comments: 6,
    createdAt: '12/12/2023',
  },
  {
    id: 6,
    name: 'Sixth Model',
    description: 'Descrição do sexto modelo...',
    status: 'backlog',
    comments: 4,
    createdAt: '13/12/2023',
  },
]
